# Generated by Django 5.1.3 on 2024-11-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_remove_questiongen_category_alter_question_quiz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(),
        ),
    ]
