# Generated by Django 5.1.3 on 2024-11-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_alter_option_option_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullstudentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
